# Assignment 2
For this assignment you'll be looking at 2017 data on immunizations from the CDC. Your datafile for this assignment is in [assets/NISPUF17.csv](assets/NISPUF17.csv). A data users guide for this, which you'll need to map the variables in the data to the questions being asked, is available at [assets/NIS-PUF17-DUG.pdf](assets/NIS-PUF17-DUG.pdf). **Note: you may have to go to your Jupyter tree (click on the Coursera image) and navigate to the assignment 2 assets folder to see this PDF file).**

## Question 1
Write a function called `proportion_of_education` which returns the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

*This function should return a dictionary in the form of (use the correct numbers, do not round numbers):* 
```
    {"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2}
```

In [13]:
import pandas as pd
df = pd.read_csv('assets/NISPUF17.csv')
df

,Unnamed: 0,SEQNUMC,SEQNUMHH,PDAT,PROVWT_D,RDDWT_D,STRATUM,YEAR,AGECPOXR,HAD_CPOX,...,XVRCTY2,XVRCTY3,XVRCTY4,XVRCTY5,XVRCTY6,XVRCTY7,XVRCTY8,XVRCTY9,INS_STAT2_I,INS_BREAK_I
0,1,128521,12852,2,NaN,235.916956,1031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,10741,1074,2,NaN,957.353840,1068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,220011,22001,2,NaN,189.611299,1050,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,86131,8613,1,675.430817,333.447418,1040,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
4,5,227141,22714,1,482.617748,278.768063,1008,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0
5,6,207941,20794,2,NaN,35.995367,1019,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,221381,22138,1,516.427723,248.916038,1008,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
7,8,182861,18286,1,313.225832,163.213401,1001,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
8,9,161121,16112,1,978.042448,718.616990,1016,2017,3.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0
9,10,143401,14340,2,NaN,1536.859533,1068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,128211,12821,1,335.398714,198.123294,1057,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
11,12,92921,9292,2,NaN,76.306250,1005,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,137041,13704,1,82.582116,45.544717,1051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
13,14,46531,4653,2,NaN,1116.347858,1025,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,87781,8778,2,NaN,168.413904,1044,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,41081,4108,2,NaN,685.693874,1036,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,188611,18861,1,345.352030,196.111859,1057,2017,NaN,2,...,VO,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
17,18,461,46,2,NaN,90.028928,1017,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,462,46,2,NaN,90.028928,1017,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,136171,13617,1,223.451930,136.912758,1059,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
20,21,270401,27040,1,249.409773,188.752870,1066,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
21,22,238751,23875,1,270.449794,134.563612,1058,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
22,23,160991,16099,1,289.125148,300.945768,1041,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
23,24,195021,19502,2,NaN,256.041114,1002,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,36011,3601,1,222.134653,99.208534,1073,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0
25,26,222341,22234,1,39.376739,16.581517,1065,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
26,27,31271,3127,1,519.601548,353.968396,1010,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
27,28,233941,23394,1,340.470079,253.165839,1002,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28,29,52581,5258,1,243.287402,193.761083,1031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0
29,30,187771,18777,1,91.660790,49.045451,1108,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28435,28436,250151,25015,1,99.480351,57.116375,2068,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28436,28437,79531,7953,1,96.617497,54.463171,2065,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
28437,28438,227671,22767,1,279.162013,120.371768,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
28438,28439,126141,12614,1,216.225073,126.221620,2052,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
28439,28440,27411,2741,2,NaN,166.040534,2051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28440,28441,266471,26647,1,180.211607,135.851907,2051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
28441,28442,6341,634,2,NaN,103.902505,2051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28442,28443,252761,25276,2,NaN,33.004856,2016,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28443,28444,97321,9732,2,NaN,100.710256,2044,2017,1.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28444,28445,146991,14699,2,NaN,263.520235,2022,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28445,28446,219991,21999,2,NaN,39.973914,2051,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28446,28447,193801,19380,1,321.058203,110.009181,2047,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0
28447,28448,136841,13684,1,593.426753,337.255316,2031,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28448,28449,237881,23788,2,NaN,390.466235,2076,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28449,28450,132081,13208,1,166.681363,96.330007,2059,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28450,28451,230881,23088,2,NaN,1007.220224,2022,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28451,28452,152371,15237,2,NaN,73.286155,2049,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28452,28453,82151,8215,1,335.456813,159.895243,2056,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0
28453,28454,122131,12213,2,NaN,33.006992,2013,2017,2.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28454,28455,191451,19145,1,59.626969,29.187316,2074,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0
28455,28456,154501,15450,2,NaN,56.655283,2062,2017,1.0,1,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28456,28457,78891,7889,2,NaN,57.484333,2028,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28457,28458,117081,11708,2,NaN,26.503010,2004,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28458,28459,120601,12060,2,NaN,288.269672,2011,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28459,28460,270341,27034,2,NaN,352.329599,2011,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28460,28461,19141,1914,2,NaN,21.188088,2062,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28461,28462,121401,12140,2,NaN,26.503010,2004,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28462,28463,128831,12883,2,NaN,27.520652,2004,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28463,28464,82921,8292,2,NaN,22.390587,2062,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28464,28465,244621,24462,2,NaN,27.520652,2004,2017,NaN,2,...,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
import pandas as pd
df = pd.read_csv('assets/NISPUF17.csv')

cont1 = 0
cont2 = 0
cont3 = 0
cont4 = 0
for num,values in df['EDUC1'].iteritems():
    if(values == 1):
        cont1 += 1
    if(values == 2):
        cont2 += 1
    if(values == 3):
        cont3 += 1
    if(values == 4):
        cont4 += 1
conttotal = len(df['EDUC1'])
prop = {"less than high school":cont1/conttotal,
        "high school":cont2/conttotal,
        "more than high school but not college":cont3/conttotal,
        "college":cont4/conttotal
       }
prop

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [51]:
def proportion_of_education():
    import pandas as pd
    df = pd.read_csv('assets/NISPUF17.csv')

    cont1 = 0
    cont2 = 0
    cont3 = 0
    cont4 = 0
    for num,values in df['EDUC1'].iteritems():
        if(values == 1):
            cont1 += 1
        if(values == 2):
            cont2 += 1
        if(values == 3):
            cont3 += 1
        if(values == 4):
            cont4 += 1
    conttotal = len(df['EDUC1'])
    prop = {"less than high school":cont1/conttotal,
            "high school":cont2/conttotal,
            "more than high school but not college":cont3/conttotal,
            "college":cont4/conttotal
           }
    return prop
    #raise NotImplementedError()

In [53]:
proportion_of_education()

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [55]:
assert type(proportion_of_education())==type({}), "You must return a dictionary."
assert len(proportion_of_education()) == 4, "You have not returned a dictionary with four items in it."
assert "less than high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "high school" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "more than high school but not college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."
assert "college" in proportion_of_education().keys(), "You have not returned a dictionary with the correct keys."

## Question 2

Let's explore the relationship between being fed breastmilk as a child and getting a seasonal influenza vaccine from a healthcare provider. Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

*This function should return a tuple in the form (use the correct numbers:*
```
(2.5, 0.1)
```

In [35]:
df = pd.read_csv('assets/NISPUF17.csv')
df = df[['CBF_01','P_NUMFLU']]
# df= df[df['P_NUMFLU'].notna()]
# NAN Values
df.isna().sum()
df = df[df['P_NUMFLU'].notna()]
df
total1 = len(df[df['CBF_01']==1])
total2 = len(df[df['CBF_01']==2])

mi = df[df['CBF_01']==1]['P_NUMFLU'].sum()
notmi = df[df['CBF_01']==2]['P_NUMFLU'].sum()

print (mi/total1 , notmi/total2)

1.8799187420058687 1.5963945918878317

In [38]:
def average_influenza_doses():
    # YOUR CODE HERE
    import pandas as pd
    df = pd.read_csv('assets/NISPUF17.csv')
    df = df[['CBF_01','P_NUMFLU']]
    # df= df[df['P_NUMFLU'].notna()]
    # NAN Values
    df.isna().sum()
    df = df[df['P_NUMFLU'].notna()]
    df
    total1 = len(df[df['CBF_01']==1])
    total2 = len(df[df['CBF_01']==2])

    mi = df[df['CBF_01']==1]['P_NUMFLU'].sum()
    notmi = df[df['CBF_01']==2]['P_NUMFLU'].sum()
#Generate tuple 
    return (mi/total1 , notmi/total2)
    #raise NotImplementedError()

In [40]:
average_influenza_doses()

(1.8799187420058687, 1.5963945918878317)

In [ ]:
assert len(average_influenza_doses())==2, "Return two values in a tuple, the first for yes and the second for no."

## Question 3
It would be interesting to see if there is any evidence of a link between vaccine effectiveness and sex of the child. Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. Return results by sex. 

*This function should return a dictionary in the form of (use the correct numbers):* 
```
    {"male":0.2,
    "female":0.4}
```

Note: To aid in verification, the `chickenpox_by_sex()['female']` value the autograder is looking for starts with the digits `0.0077`.

In [44]:
df = pd.read_csv('assets/NISPUF17.csv')
df = df[df['P_NUMVRC']>=1]
x = df[df['HAD_CPOX']==1]
y = df[df['HAD_CPOX']==2]
# create a dictionary 

dict={}

# m = male , f = female , inf = infected , not_inf = not infected
m_inf = len(x[x['SEX']==1])
m_not_inf = len(y[y['SEX']==1])

f_inf = len(x[x['SEX']==2])
f_not_inf = len(y[y['SEX']==2])

dict['male'] = m_inf / m_not_inf
dict['female'] = f_inf / f_not_inf
dict

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

In [45]:
def chickenpox_by_sex():
    # YOUR CODE HERE
    import pandas as pd
    df = pd.read_csv('assets/NISPUF17.csv')
    df = df[df['P_NUMVRC']>=1]
    x = df[df['HAD_CPOX']==1]
    y = df[df['HAD_CPOX']==2]
    # create a dictionary 

    dict={}

    # m = male , f = female , inf = infected , not_inf = not infected
    m_inf = len(x[x['SEX']==1])
    m_not_inf = len(y[y['SEX']==1])

    f_inf = len(x[x['SEX']==2])
    f_not_inf = len(y[y['SEX']==2])

    dict['male'] = m_inf / m_not_inf
    dict['female'] = f_inf / f_not_inf
    return dict
    raise NotImplementedError()

In [48]:
chickenpox_by_sex()

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

In [50]:
assert len(chickenpox_by_sex())==2, "Return a dictionary with two items, the first for males and the second for females."

## Question 4
A correlation is a statistical relationship between two variables. If we wanted to know if vaccines work, we might look at the correlation between the use of the vaccine and whether it results in prevention of the infection or disease [1]. In this question, you are to see if there is a correlation between having had the chicken pox and the number of chickenpox vaccine doses given (varicella).

Some notes on interpreting the answer. The `had_chickenpox_column` is either `1` (for yes) or `2` (for no), and the `num_chickenpox_vaccine_column` is the number of doses a child has been given of the varicella vaccine. A positive correlation (e.g., `corr > 0`) means that an increase in `had_chickenpox_column` (which means more no’s) would also increase the values of `num_chickenpox_vaccine_column` (which means more doses of vaccine). If there is a negative correlation (e.g., `corr < 0`), it indicates that having had chickenpox is related to an increase in the number of vaccine doses.

Also, `pval` is the probability that we observe a correlation between `had_chickenpox_column` and `num_chickenpox_vaccine_column` which is greater than or equal to a particular value occurred by chance. A small `pval` means that the observed correlation is highly unlikely to occur by chance. In this case, `pval` should be very small (will end in `e-18` indicating a very small number).

[1] This isn’t really the full picture, since we are not looking at when the dose was given. It’s possible that children had chickenpox and then their parents went to get them the vaccine. Does this dataset have the data we would need to investigate the timing of the dose?

In [ ]:
 # this is just an example dataframe
    df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),
                   "num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})

    # here is some stub code to actually run the correlation
    corr, pval=stats.pearsonr(df["had_chickenpox_column"],df["num_chickenpox_vaccine_column"])

In [65]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # YOUR CODE HERE
    df = pd.read_csv('assets/NISPUF17.csv')
    df = df[['HAD_CPOX', 'P_NUMVRC']]
    df = df[df['HAD_CPOX']<=3]
    df = df[df['P_NUMVRC'].notna()]
    
    # run the correlation
    corr, pval=stats.pearsonr(df["HAD_CPOX"],df["P_NUMVRC"])
    return corr
    raise NotImplementedError()

In [59]:
# df = pd.read_csv('assets/NISPUF17.csv')
# df['HAD_CPOX'].unique()

In [67]:
corr_chickenpox()

0.07044873460147986

In [66]:
assert -1<=corr_chickenpox()<=1, "You must return a float number between -1.0 and 1.0."